
alarm[0] = room_speed * 3;
global.can_take_damage = true;
global.damage_cooldown = 0;
global.gold = 10
global.gold_mod = 1
global.xp = 0
global.xp_mod = 1
global.cur_tower_hp = 10
global.max_tower_hp = 10
global.dmg = 5
global.crit_mod = 0.01
global.crit_dmg_mod = 2
global.attack_speed = 1
global.hp_regen = 0
global.UI_Layer = layer_create(100, "UI");
global.tower_armor = 0
global.tower_armor_percent = 0
global.tower_thorns_damage = 0
global.xp_to_up = 10
global.current_level = 1
global.shot_count = 1
global.shot_count_chance = 0
global.multishot_chance = 0
global.multishot_count = 1
global.attack_radius = 300
global.bounce_shot_chance = 0
global.bounce_shot_count = 0
global.life_stealing = 0
global.enemy_speed_mult = 1
global.pause = false
can_heal = true
heal_cooldown = 0
